export class UserTypes {
    public static readonly COMPANY_USER = 1;
    public static readonly ARAI_USER = 2;
   
}

export enum USER_ROLES {
    
    //Company Roles
    COMPANY_ADMIN = 'COMPANY_ADMIN',
    COMPANY_SUB_ADMIN = 'COMPANY_SUB_ADMIN',
    COMPANY_USER = 'COMPANY_USER',

    //ARAI
    CMVR_TAS_ADMIN = 'CMVR_TAS_ADMIN',
    HMR_ADMIN = 'HMR_ADMIN',
    PROJECT_ADMIN = 'PROJECT_ADMIN',
    CERTIFICATION_HOD = 'CERTIFICATION_HOD',
    FILE_COORDINATOR ='FILE_COORDINATOR',
    CERTIFICATE_HANDLER='CERTIFICATE_HANDLER',
    DEPT_HOD='DEPT_HOD',
    DEPT_ADMIN='DEPT_ADMIN',
    TEST_ENGINEER='TEST_ENGINEER',
    REPORT_HANDLER='REPORT_HANDLER'



}