export enum APP_SETTING {
    DATE_FORMAT = 'DATE_FORMAT',
    DATE_TIME_FORMAT = 'DATE_TIME_FORMAT',
    USE_GLOBAL_DATE_TIME_FORMAT = 'useglobaldatetimeformat',
    RESEND_OTP_TIME_SEC = "RESEND_OTP_TIME_SEC",
    USE_SAML = "USE_SAML",
    MAX_USER_ADD_COUNT = "MAX_USER_ADD_COUNT"
}


export enum EVENT_NAME {
    ON_ITEM_CLICK = "item_click",
    ON_SUBMIT = "on_submit",
    ON_ADD_CLICK = "add_click",
    ON_UPLOAD_CLICK = "upload",
    ON_DOWNLOAD_ALL_CLICK = "download_all_click",
    ON_EXPORT_CLICK = "export_click",
    ON_SYNC_CLICK = "sync_click",
    ON_EMAIL_CLICK = "email_click",

    ON_CANCEL = "on_cancel",
    ON_SHORT_CLOSE = "on_short_close",
    ON_UNDER_SHORT_CLOSE = "on_under_short_close",
    ON_PARTIAL_CLOSE = "on_partial_close",
    ON_REJECT = "on_reject",

    ON_CLEARANCE_FORWARD_TO_FC = "on_forwardToFc",
    ON_CLEARANCE_RETURN_TO_ENG = "on_returnToEngineer",
    ON_CLEARANCE_APPROVE_BY_FC  ="on_approveClearanceByFc",
    ON_CLEARANCE_RETURN_TO_DEPT = "on_returnToDept",
    ON_CLEARANCE_FORWARD_TO_HMR_ADMIN= "on_forwardToHmrAdmin",

    ON_START= "on_start",
    ON_STOP= "on_stop",
    ON_ADD_TAG= "on_add_tag",
    ON_ADD_QUERY= "on_add_query",
    ON_FILTER_APPLY= "on_filter_apply",
    ON_FILTER_RESET = "on_filter_reset"
}




export enum MASTER_DATA {
    FUEL_TYPE = 'FUEL_TYPE',
    VEHICLE_ENGINE_CATEGORY = 'VEHICLE_ENGINE_CATEGORY',
    EMISSION_NORMS = 'EMISSION_NORMS',
    NATURE_OF_BUSINESS = 'NATURE_OF_BUSINESS',
    ORGANIZATION_TYPE = 'ORGANIZATION_TYPE',
    LOCATION_TYPE = 'LOCATION_TYPE',
    STATE = 'STATE',
    ACCOUNT_TYPE = 'ACCOUNT_TYPE',
    DOCUMENT_SUBMISSION_TYPE = 'DOCUMENT_SUBMISSION_TYPE',
    REPORT_CERTIFICATES = 'REPORT_CERTIFICATES',
    OTHER_CERTIFICATES = 'OTHER_CERTIFICATES',
    CMVR_CERTIFICATES = 'CMVR_CERTIFICATES',
    TYPE_OF_CERTIFICATE = 'TYPE_OF_CERTIFICATE',
    CASE_DOCUMENT = 'CASE_DOCUMENT',
    USER_ROLES = 'USER_ROLES',
    COMPANY_USER_ROLES = 'COMPANY_USER_ROLES',
    COMPONENT_TYPES = 'COMPONENT_TYPES',
    CASE_STATUS = 'CASE_STATUS',
    CUSTOMER_STATUS = 'CUSTOMER_STATUS',
    DOCUMENT_TYPE = "DOCUMENT_TYPE",
    CASE_DEPARTMENT_STATUS = "CASE_DEPARTMENT_STATUS",
    CASE_TYPE = "CASE_TYPE",
    CASE_PRIORITY = "CASE_PRIORITY",
    CASE_REM_ACCESS_SPECIFIER = "CASE_REM_ACCESS_SPECIFIER",
    CASE_REMARK_ACTIONS = 'CASE_REMARK_ACTIONS',
    ARAI_DEPARTMENTS = 'ARAI_DEPARTMENTS',
    PARTY_STATUS = 'PARTY_STATUS',
    CASE_DOCUMENT_TYPE = 'CASE_DOCUMENT_TYPE',
    CASE_QUERY_TAGS = "CASE_QUERY_TAGS",
    CLEARANCE_NOTE_STATUS = "CLEARANCE_NOTE_STATUS",
    CLEARANCE_MODE = "CLEARANCE_MODE",
    CL_NOTE_TEST_RPT_UPLOADED="CL_NOTE_TEST_RPT_UPLOADED",
    CL_NOTE_FINACE_CLEARED = "CL_NOTE_FINACE_CLEARED",
    SHORT_CLOSE_REASON="SHORT_CLOSE_REASON",
    DISPATCH_TRANSPORT_TYPE="DISPATCH_TRANSPORT_TYPE",
    CASE_IMPACT_TYPE="CASE_IMPACT_TYPE",
    CASE_QUERY_TYPE="CASE_QUERY_TYPE"
}


export enum CASE_STATUS {
    DRAFT_CS = 'DRAFT_CS',
    UNDER_SHORT_CLOSE = 'UNDER_SHORT_CLOSE',
    IN_PROGRSS = 'IN_PROGRSS',
    REJECTED = 'REJECTED',
    CASE_APPROVED = 'CASE_APPROVED',
    SUBMITTED = 'SUBMITTED',
    REVIEW = 'REVIEW',
    ASSIGNED = 'ASSIGNED',
    CERTIFIED = 'CERTIFIED',
    COMPLETED = 'COMPLETED',
    ALLOCATED = 'ALLOCATED',
    ALLOTED_TO_ENGINEER = 'ALLOTED_TO_ENGINEER',
    FORWARDED_FOR_CERTIFICATE = 'FORWARDED_FOR_CERTIFICATE',
    CUSTOMER_CANCEL = 'CUSTOMER_CANCEL',
    PARTIAL_CLOSE = 'PARTIAL_CLOSE',
    SHORT_CLOSED = 'SHORT_CLOSED',
    SHOR_CLOSE_VERIFICATION = 'SHOR_CLOSE_VERIFICATION',
    ON_GOING = "ON_GOING",
    FINAL_SCRUTINY = "FINAL_SCRUTINY",
    UNDER_CERTIFICATION = "UNDER_CERTIFICATION"
}

export enum ENGINEER_WORKING_STATUS {
    SCR_START = 'SCR_START',
    SCR_STOP = 'SCR_STOP',
    SCR_COMPLETED = 'SCR_COMPLETED'
}

export enum QUERY_TYPES_ID {
    CQT_GENERIC = 11461,
    CQT_DOCUMENTS = 11462
}

export enum TAGS_TYPES_ID {
    OTHER_TAG =  10960
}

export enum TAGS_TYPES_CODE {
    OTHER_TAG =  'OTHER_TAG'
}

export enum USER_ROLE_TYPE{
    HMR_ADMIN = 10923
}

export enum APP_DATA_CODE{
    CASE_STATUS_DRAFT = "DRAFT_CS"
}


export enum CASE_IMPACT_TYPE_ID {
    NO_IMPACT = 11457,
    TEST_DELAY = 11458,
    TEST_ON_HOLD = 11459,
    CLEARANCE_ON_HOLD = 11460
}